// Frozen measurement results.
//
// These are eval outputs, not run outputs, so they do not belong in demo.json
// (which is a projection of a single batch). Source of truth is
// docs/eval/corpus_test70_v2.md and docs/eval/holdout70_v2.md, both generated
// offline with zero API calls and committed to the repo.
//
// The test split was executed once on llama-3.3-70b-versatile, prompt v1, with
// 100/100 rows verified as single-tier before any accuracy was computed.

export interface Metric {
  label: string;
  value: string;
  detail?: string;
}

export const HEADLINE: Metric[] = [
  {
    label: "Type accuracy",
    value: "88.0%",
    detail: "88/100 held-out · 95% CI [80.2, 93.0]",
  },
  {
    label: "Keyword-floor baseline",
    value: "47.0%",
    detail: "same split, no model · +41.0 pts uplift",
  },
  {
    label: "Cross-family holdout",
    value: "92.5%",
    detail: "40 Gemini-generated · CI [80.1, 97.4]",
  },
  {
    label: "Branch completion",
    value: "100%",
    detail: "100/100 test · 40/40 holdout",
  },
];

export const SECONDARY: Metric[] = [
  { label: "Urgency within-one", value: "91.0%", detail: "exact 52.0%" },
  { label: "Calibration error (ECE)", value: "0.027", detail: "3 confidence levels" },
  { label: "Test tokens", value: "63,906", detail: "~639 per case" },
];

export const EVAL_NOTE =
  "Corpus is LLM-generated; the cross-family holdout is generated by a " +
  "different model family and converges, which is the check on that caveat. " +
  "Full reports, confusion matrices and per-class CIs in docs/eval/.";
