// Frozen measurement results.
//
// These are eval outputs, not run outputs, so they do not belong in demo.json
// (which is a projection of a single batch). Source of truth is
// docs/eval/corpus_test70_v2.md and docs/eval/holdout70_v2.md, both generated
// offline with zero API calls and committed to the repo.
//
// The test split was executed once on llama-3.3-70b-versatile, prompt v1, with
// 100/100 rows verified as single-tier before any accuracy was computed.
//
// `caption` renders on the card face, always visible: the sample size or
// interval belongs next to the number it qualifies, not behind a hover. One
// fact per caption, one line, never wrapping -- a caption that wraps makes its
// card taller than its neighbours and reads as clutter rather than density.
// Keep these at or under 26 characters. The methodology note (EVAL_NOTE) is
// the one hint left on this section.
export interface Metric {
  label: string;
  value: string;
  caption?: string;
}
export const HEADLINE: Metric[] = [
  {
    label: "Type accuracy",
    value: "88.0%",
    caption: "88/100 · CI 80.2–93.0",
  },
  {
    label: "Keyword-floor baseline",
    value: "47.0%",
    caption: "same split · +41.0 pts",
  },
  {
    label: "Cross-family holdout",
    value: "92.5%",
    caption: "40 rows · model-only 97.5%",
  },
  {
    label: "Branch completion",
    value: "100%",
    caption: "100/100 · 40/40",
  },
];
export const SECONDARY: Metric[] = [
  { label: "Urgency within-one", value: "91.0%", caption: "exact 52.0%" },
  {
    label: "Calibration error (ECE)",
    value: "0.027",
    caption: "3 confidence levels",
  },
  { label: "Test tokens", value: "63,906", caption: "~639 per case" },
];
export const EVAL_NOTE =
  "Corpus is LLM-generated; the cross-family holdout is generated by a " +
  "different model family and converges, which is the check on that caveat. " +
  "Full reports, confusion matrices and per-class CIs in docs/eval/.";
