#!/usr/bin/env python3
"""
Data gates for a generated corpus file. Row count proves nothing; these are
the checks that caught a two-thirds-duplicate corpus and a contaminated
`other` class on earlier runs.

Gates:
  1. uniqueness of normalised bodies  >= 95%
  2. no overlap with an existing corpus file (holdout must be genuinely new)
  3. all five classes present; hardship never low-urgency
  4. length distribution plausible, and short bodies PRINTED for inspection
  5. optional single-family check (--single-family), for the cross-family
     holdout only
  6. per-class sample printed for the mandatory eyeball audit

Single-family is opt-in by design. The main corpus is EXPECTED to contain
rows from more than one model: the generation waterfall degrades to the
secondary Groq model under TPM pressure, and that is the resilience feature
working, not a defect. Only the cross-family holdout must come from exactly
one non-Groq model, because a "cross-family" set quietly produced by the
fallback would be worthless and would look fine in the output.

Exit code is non-zero if a hard gate fails, so it can gate a commit.

Run from the repo root:
    python3 scripts/diag/gate_corpus.py data/corpus/corpus.jsonl
    python3 scripts/diag/gate_corpus.py data/corpus/holdout.jsonl \\
        --against data/corpus/corpus.jsonl --single-family gemini-3.6-flash
"""

import argparse
import json
import pathlib
import statistics
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[2]


def normalise(text):
    return " ".join(text.lower().split())


def load(path):
    p = pathlib.Path(path)
    if not p.is_absolute():
        p = ROOT / p
    if not p.exists():
        sys.exit(f"missing file: {p}")
    return [json.loads(line) for line in open(p, encoding="utf-8") if line.strip()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path")
    ap.add_argument("--against", default=None, help="file that must not overlap")
    ap.add_argument("--samples", type=int, default=2, help="bodies to print per class")
    ap.add_argument("--min-unique", type=float, default=0.95)
    ap.add_argument(
        "--single-family",
        default=None,
        metavar="MODEL",
        help="hard-fail if any row was generated by a different model "
        "(cross-family holdout only)",
    )
    ap.add_argument("--short-threshold", type=int, default=60)
    args = ap.parse_args()

    rows = load(args.path)
    n = len(rows)
    failures = []
    print(f"== {args.path}: {n} rows ==")

    bodies = [normalise(r["body"]) for r in rows]
    uniq = len(set(bodies))
    frac = uniq / n if n else 0.0
    ok = frac >= args.min_unique
    print(
        f"\n[{'PASS' if ok else 'FAIL'}] uniqueness: {uniq}/{n} ({frac:.1%}), "
        f"bar {args.min_unique:.0%}"
    )
    if not ok:
        failures.append("uniqueness")
        for d in [b for b, c in Counter(bodies).items() if c > 1][:3]:
            print(f"        repeated: {d[:90]}...")

    if args.against:
        other = {normalise(r["body"]) for r in load(args.against)}
        clash = [b for b in bodies if b in other]
        print(
            f"[{'PASS' if not clash else 'FAIL'}] overlap with {args.against}: "
            f"{len(clash)} shared bodies"
        )
        if clash:
            failures.append("overlap")
            print(f"        example: {clash[0][:90]}...")

    print("\n-- distribution --")
    by_type = Counter(r["true_type"] for r in rows)
    for t, c in sorted(by_type.items()):
        print(f"   {t:<20} {c:>3}  ({c / n:.0%})")

    hard_low = [
        r
        for r in rows
        if r["true_type"] == "financial_hardship" and r["true_urgency"] == "low"
    ]
    print(
        f"[{'PASS' if not hard_low else 'FAIL'}] hardship never low-urgency: "
        f"{len(hard_low)} violations"
    )
    if hard_low:
        failures.append("hardship-low")

    expected = (
        "billing_dispute",
        "financial_hardship",
        "general_enquiry",
        "service_request",
        "other",
    )
    empty = [t for t in expected if by_type.get(t, 0) == 0]
    print(
        f"[{'PASS' if not empty else 'FAIL'}] all five classes present: "
        f"missing {empty or 'none'}"
    )
    if empty:
        failures.append("missing-class")

    lens = [len(r["body"]) for r in rows]
    print("\n-- body length (chars) --")
    print(
        f"   min {min(lens)}  median {int(statistics.median(lens))}  "
        f"mean {int(statistics.mean(lens))}  max {max(lens)}"
    )
    if len(set(lens)) < max(3, n // 10):
        print("[WARN] length distribution looks collapsed - check for templating")

    short = sorted(
        (r for r in rows if len(r["body"]) < args.short_threshold),
        key=lambda r: len(r["body"]),
    )
    if short:
        print(
            f"\n[INSPECT] {len(short)} bod(ies) under {args.short_threshold} "
            "chars - terse is legitimate, truncated is not:"
        )
        for r in short[:8]:
            body = " ".join(r["body"].split())
            print(
                f"   {len(r['body']):>4}ch  {r['example_id']:<34} "
                f"[{r['true_type']}]  {body!r}"
            )

    gen = Counter(r.get("generated_by") for r in rows)
    print(f"\n-- generated_by: {dict(gen)} --")
    if args.single_family:
        wrong = [r for r in rows if r.get("generated_by") != args.single_family]
        print(
            f"[{'PASS' if not wrong else 'FAIL'}] single-family "
            f"({args.single_family}): {len(wrong)} foreign rows"
        )
        if wrong:
            failures.append("single-family")
            print(
                "        a cross-family holdout produced by a fallback is not "
                "cross-family - delete those rows and regenerate"
            )
            for r in wrong[:3]:
                print(f"        {r['example_id']} <- {r.get('generated_by')}")
    else:
        degraded = sum(1 for r in rows if r.get("degraded"))
        print(
            f"[INFO] rows from a fallback provider: {degraded} "
            "(expected for the main corpus; the waterfall degrades under "
            "TPM pressure by design). Use --single-family for the holdout."
        )

    if args.samples:
        print("\n-- MANDATORY EYEBALL AUDIT --")
        seen = Counter()
        for r in rows:
            t = r["true_type"]
            if seen[t] >= args.samples:
                continue
            seen[t] += 1
            body = " ".join(r["body"].split())
            print(f"\n [{t} / {r['true_urgency']}] {r['example_id']}")
            print(f"   subj: {r.get('subject', '')[:80]}")
            print(f"   {body[:300]}{'...' if len(body) > 300 else ''}")

    print("\n" + "=" * 60)
    if failures:
        print(f"GATES FAILED: {', '.join(failures)} - do not commit")
        sys.exit(1)
    print("ALL HARD GATES PASSED - now read the samples above before committing")


if __name__ == "__main__":
    main()
